// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkXrgmCTghWMeSBTIvYXjT-xNqEMlF9Dw',
    appId: '1:96145665483:web:9a6c6a89b9182429605a4e',
    messagingSenderId: '96145665483',
    projectId: 'tugaskuliah-be662',
    authDomain: 'tugaskuliah-be662.firebaseapp.com',
    storageBucket: 'tugaskuliah-be662.appspot.com',
    measurementId: 'G-Z33S0R8QH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_eylhR-FVcGLrqSsi0L0G2MvR0bJs6jM',
    appId: '1:96145665483:android:f61a29d8ceaf24a1605a4e',
    messagingSenderId: '96145665483',
    projectId: 'tugaskuliah-be662',
    storageBucket: 'tugaskuliah-be662.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-8chFE1KlHizWws5I8MAghsQL4p-55SY',
    appId: '1:96145665483:ios:22bb9aec103f7b0a605a4e',
    messagingSenderId: '96145665483',
    projectId: 'tugaskuliah-be662',
    storageBucket: 'tugaskuliah-be662.appspot.com',
    iosClientId: '96145665483-gal7loc2liibb81qfg1r84thauco8b0j.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
